# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "levelup 0x06"
version: "0.1"
con_datetime: "2020-05-09 17:00:00"
con_timezone: "UTC"
description: "LevelUp is Bugcrowd’s live information security conference, conducted entirely online via Youtube, Twitch, and Discord."
email: casey@bugcrowd.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://levelup.sh" # the base hostname & protocol for your site

# Markdown parser
#
# Syntax reference: https://kramdown.gettalong.org/syntax.html
markdown: kramdown

# Files to exclude from builds.
exclude:
  - .jekyll-cache/
  - .gitignore
  - .gitmodules
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - scripts/