# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: levelup
version: "0.1"
description: "$ cat index.md"
email: casey@bugcrowd.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://levelup.sh" # the base hostname & protocol for your site

# Markdown parser
#
# Syntax reference: https://kramdown.gettalong.org/syntax.html
markdown: kramdown

# Files to exclude from builds.
exclude:
  - .jekyll-cache/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - scripts/