# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "#LevelUp"
version: "0x06"
rego_url: "https://www.bugcrowd.com/resources/levelup0x06/registration/"
con_datetime: "2020-05-09T:10:00-07:00"
timezone: America/Los_Angeles # Used for site generation rubt TZ timestamping.
con_timezone: "PDT"
con_duration: "6" # in hours
description: "LevelUp is Bugcrowd’s live information security conference, conducted entirely online via Youtube, Twitch, and Discord."
email: casey+levelup@bugcrowd.com

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://levelup.sh" # the base hostname & protocol for your site

# Markdown parser
#
# Syntax reference: https://kramdown.gettalong.org/syntax.html
markdown: kramdown

include: [".well-known/matrix/client", ".well-known/matrix/server"]

# Files to exclude from builds.
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - scripts/
